# get current HDD temperature in C
UserParameter=hdd.temp[*],smartctl -a /dev/$1|grep Temperature_Celsius|awk '{print $$10}'
UserParameter=hdd.reallocated.sectors[*],smartctl -a /dev/$1|grep -i Reallocated_Sector_Ct|awk '{print $$10}'
