- name: Fail if task is run on non-Debian12 system
  ansible.builtin.fail:
    msg: The supported OS for this role is Debian12 only
  when: ansible_os_family != "Debian" or ansible_distribution_major_version != "12"

- name: Install zabbix release repo for DEBIAN family
  apt:
    deb: "https://repo.zabbix.com/zabbix/7.0/debian/pool/main/z/zabbix-release/zabbix-release_latest%2Bdebian12_all.deb"

- name: Install zabbix-agent package
  apt:
    name: "{{ pkg_name }}"
    state: latest
    update_cache: yes

- name: Push zabbix PSK file
  copy:
    src: zabbix_agent.psk
    dest: /etc/zabbix/zabbix_agentd.psk
    owner: zabbix
    group: zabbix
    mode: '0600'

- name: Push zabbix agent conf via template
  template:
    src: zabbix_agent2.conf.j2
    dest: /etc/zabbix/zabbix_agent2.conf

- name: Enable zabbix-agent service
  service:
    name: "{{ pkg_name }}"
    enabled: true

- name: Restart zabbix-agent service
  service:
    name: "{{ pkg_name }}"
    state: restarted


    #- name: Create a new host or update an existing host's info
    #  vars:
    #    ansible_network_os: community.zabbix.zabbix
    #    ansible_connection: httpapi
    #    ansible_httpapi_port: 443
    #    ansible_httpapi_use_ssl: true
    #    ansible_httpapi_validate_certs: false
    #    ansible_host: zabbix.spiak.sk
    #  become: false
    #  community.zabbix.zabbix_host:
    #

- name: Update zabbix host via API
  vars:
    ansible_network_os: community.zabbix.zabbix
    ansible_connection: httpapi
    ansible_zabbix_url_path: ''
    ansible_httpapi_port: 443
    ansible_httpapi_use_ssl: true
    ansible_httpapi_validate_certs: false
    ansible_user: '{{ user }}'
    ansible_httpapi_pass: '{{ password }}'
    #ansible_host: zabbix.spiak.sk # you can use task level ansible_host or delegate_to like in previous example
  become: false
  delegate_to: zabbix.spiak.sk
  community.zabbix.zabbix_host:
    host_name: "{{ ansible_hostname }}"
    host_groups:
      - Location/API
    link_templates:
      - Template OS Linux active
    status: enabled
    state: present
    interfaces:
      - type: 1
        main: 1
        useip: 1
        ip: "{{ ansible_default_ipv4.address }}"
        port: 10050
    tls_psk_identity: "{{ ansible_hostname }}"
    tls_connect: 2
    tls_accept: 2
    tls_psk: bc061dfcf122ca98ca112729d1322737ee913f87ff98c1b80d9b9c288eaa59c5
    force: false
  when: password is defined
