---
- name: Create cron job to update oh-my-zsh daily at 2am
  ansible.builtin.cron:
    name: "job to update oh-my-zsh daily at 2am"
    minute: "0"
    hour: "2"
    job: "/bin/zsh -c 'omz update' >/dev/null 2>&1"
    state: present
