---
- name: Create cron job to restart earnapp daily at 4am
  ansible.builtin.cron:
    name: "Restart earnapp service"
    minute: "0"
    hour: "4"
    job: "/bin/systemctl restart earnapp > /dev/null 2>&1"
    state: present
